name: obsi_flutter_example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  obsi: ^1.0.0
  obsi_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
